# Configuración de la Base de Datos (Neon)
spring.datasource.url=jdbc:postgresql://ep-old-mountain-apwqgc3i-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vQRMoOZE92fP
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logs
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.orm.jpa=INFO

# Puerto (Railway asigna el puerto dinámicamente via variable PORT)
server.port=${PORT:8081}


# Configuración del servidor de correos (GMAIL API - HTTP)
# Usamos el puerto 443 (HTTPS) para evitar bloqueos de SMTP en Railway
google.gmail.client-id=310828199681-1i07efjg56b9p2r2fc639jsadcs0jlh0.apps.googleusercontent.com
google.gmail.client-secret=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
google.gmail.refresh-token=1//04-8icNQ5yz9YCgYIARAAGAQSNwF-L9IreZV__E_k4J45p-7Xg5u_SMzkgivaw9DthuM5Fkh5Rsxj39eK_A1ucRu7xANrwQsB9Ck
spring.mail.username=jimmyvelandia@outlook.es