# Configuración de la Base de Datos (Neon)
spring.datasource.url=jdbc:postgresql://ep-old-mountain-apwqgc3i-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vQRMoOZE92fP
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logs
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.orm.jpa=INFO

# Puerto (Railway asigna el puerto dinámicamente via variable PORT)
server.port=${PORT:8081}


# Configuración del servidor de correos (Gmail Gratis)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jimmydfrancovo@ufps.edu.co

# ⚠️ Aquí va la clave de 16 letras amarillas que te dio Google (¡Sin espacios!)
# Lo ideal es dejar la variable de entorno para que la pegues en Railway de forma segura
spring.mail.password=${GMAIL_SMTP_PASSWORD:}

# Propiedades de seguridad obligatorias de JavaMail para Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true