/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#735c00",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-container": "#4e3d00",
        "surface-container-high": "#e6e8ea",
        "background": "#f7f9fb",
        "error": "#ba1a1a",
        "primary-fixed": "#d6e3ff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "outline": "#74777f",
        "secondary-fixed": "#d3e4ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "on-primary-container": "#86a0cd",
        "on-secondary-fixed": "#001c38",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "tertiary-container": "#cba72f",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffe088",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed-dim": "#adc7f7",
        "on-surface-variant": "#43474e",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-tint": "#455f88",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00477f",
        "surface": "#f7f9fb",
        "inverse-primary": "#adc7f7",
        "outline-variant": "#c4c6cf",
        "tertiary-fixed-dim": "#e9c349",
        "surface-dim": "#d8dadc",
        "primary-container": "#1a365d",
        "primary": "#002045",
        "academic-gold": "#CEAE42",
        "mini-gray": "#F2F4F6",
        "elegant-gray": "#696C6E",
        "secondary-container": "#7db6ff",
        "secondary-fixed-dim": "#a2c9ff",
        "secondary": "#1960a3",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004881",
        "on-tertiary-fixed": "#241a00",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#574500"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
}
